/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for identify
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/identify.h>

#include <interfaces/identify.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * IdentifyBase = NULL;
static struct Library * __IdentifyBase = NULL;

/****************************************************************************/

void identify_base_constructor(void)
{
    if (IdentifyBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __IdentifyBase = IdentifyBase = IExec->OpenLibrary("identify.library", 0);
    if (IdentifyBase == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to open 'identify.library'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzz"))) static void
(*identify_base_constructor_ptr)(void) USED = identify_base_constructor;

/****************************************************************************/

void identify_base_destructor(void)
{
    if (__IdentifyBase != NULL)
    {
        IExec->CloseLibrary(__IdentifyBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*identify_base_destructor_ptr)(void) USED = identify_base_destructor;

/****************************************************************************/

