
/* This file was generated by idltool 53.24. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_IDENTIFY_H
#include <libraries/identify.h>
#endif

/* forward declaration */
struct IdentifyIFace;

extern ULONG                VARARGS68K _Identify_Obtain(struct IdentifyIFace *);
extern ULONG                VARARGS68K _Identify_Release(struct IdentifyIFace *);
extern LONG                 VARARGS68K _Identify_IdExpansion(struct IdentifyIFace *, struct TagItem * Tags);
extern STRPTR               VARARGS68K _Identify_IdHardware(struct IdentifyIFace *, ULONG value, struct TagItem * Tags);
extern LONG                 VARARGS68K _Identify_IdAlert(struct IdentifyIFace *, ULONG value, struct TagItem * Tags);
extern void                 VARARGS68K _Identify_IdFunction(struct IdentifyIFace *, STRPTR str, LONG value, struct TagItem * Tags);
extern ULONG                VARARGS68K _Identify_IdHardwareNum(struct IdentifyIFace *, ULONG value, struct TagItem * Tags);
extern void                 VARARGS68K _Identify_IdHardwareUpdate(struct IdentifyIFace *);
extern void                 VARARGS68K _Identify_IdFormatString(struct IdentifyIFace *, STRPTR str1, STRPTR str2, struct TagItem * Tags);
extern ULONG                VARARGS68K _Identify_IdEstimateFormatSize(struct IdentifyIFace *, STRPTR str, struct TagItem * Tags);
