
/* This file was generated by idltool 53.24. Do not edit */

#include "identify_vectors.h"

STATIC uint32 VARARGS68K _Identify_UNIMPLEMENTED(struct IdentifyIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _Identify_Obtain,
    _Identify_Release,
    _Identify_UNIMPLEMENTED, /* Expunge */
    _Identify_UNIMPLEMENTED, /* Clone */
    _Identify_IdExpansion,
    _Identify_IdHardware,
    _Identify_IdAlert,
    _Identify_IdFunction,
    _Identify_IdHardwareNum,
    _Identify_IdHardwareUpdate,
    _Identify_IdFormatString,
    _Identify_IdEstimateFormatSize,
    (APTR)-1
};
