#ifndef INLINE4_IDENTIFY_H
#define INLINE4_IDENTIFY_H

/*
** This file was auto generated by idltool 53.24.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_IDENTIFY_H
#include <libraries/identify.h>
#endif
#include <interfaces/identify.h>

/* Inline macros for Interface "main" */
#define IdExpansion(Tags) IdentifyIFace->IdExpansion((Tags))
#define IdHardware(value, Tags) IdentifyIFace->IdHardware((value), (Tags))
#define IdAlert(value, Tags) IdentifyIFace->IdAlert((value), (Tags))
#define IdFunction(str, value, Tags) IdentifyIFace->IdFunction((str), (value), (Tags))
#define IdHardwareNum(value, Tags) IdentifyIFace->IdHardwareNum((value), (Tags))
#define IdHardwareUpdate() IdentifyIFace->IdHardwareUpdate()
#define IdFormatString(String, Buffer, BufferLength, Tags) IdentifyIFace->IdFormatString((String), (Buffer), (BufferLength), (Tags))
#define IdEstimateFormatSize(str, Tags) IdentifyIFace->IdEstimateFormatSize((str), (Tags))

#endif /* INLINE4_IDENTIFY_H */
